# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: multi-agent-custom-automation-engine-solution-accelerator
metadata:
  template: multi-agent-custom-automation-engine-solution-accelerator@1.0
requiredVersions:
  azd: '>= 1.18.0 != 1.23.9'

services:
  backend:
    project: ./src/backend
    language: py
    host: containerapp
    docker:
      path: ./Dockerfile.NoCache
      image: backend
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      remoteBuild: true
  
  mcp:
    project: ./src/mcp_server
    language: py
    host: containerapp
    docker:
      image: mcp
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      remoteBuild: true

  frontend:
    project: ./src/App
    language: py
    host: appservice
    dist: ./dist
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run: ../../infra/scripts/build/package_frontend.ps1
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run: bash ../../infra/scripts/build/package_frontend.sh
          interactive: true
          continueOnError: false

hooks:
  postdeploy:
    windows:
      run: infra/scripts/post-provision/post_deploy.ps1
      shell: pwsh
      interactive: true
    posix:
      run: bash infra/scripts/post-provision/post_deploy.sh
      shell: sh
      interactive: true